### ISSUE TITLE
**Költőválasztás**

### ISSUE THREAD

**Issue by borsodi-koppany** [borsodi-koppany/Tavaszi-versek-B#1]
keressünk költőktől olyan verseket, amikben benne van a tavasz szó, 3költőtől 3 vers

**Comment by borsodi-koppany** [comment]
Kik legyenek a költőkök?

**Comment by fatura-brigitta** [comment]
Megbeszélve, de rendelj hozzá minket a feladathoz, hogy valid legyen

**Comment by feher-kristof1** [comment]
Mi lenne, ha egy valaki egy költőről írna?

**Comment by feher-kristof1** [comment]
Akkor csak 3 verset kell keresni, és úgyis egy helyen lesznek.

**Comment by feher-kristof1** [comment]
Sure, ha a Koppánynak is OK.

**Comment by feher-kristof1** [comment]
Hogy álltok?

**Comment by borsodi-koppany** [comment]
én csinálom Petőfit

**Comment by feher-kristof1** [comment]
ok

**Comment by borsodi-koppany** [comment]
hallod Kristóf töröld ki a branchedet pls mert most azt veszi default branchnak

**Comment by borsodi-koppany** [comment]
és kéne külön master

**Comment by borsodi-koppany** [comment]
már töröltem, az issueből kéne branchet csinálnod

**Comment by feher-kristof1** [comment]
Ok

**Comment by feher-kristof1** [comment]
Akkor a mostani master az nem az én brenchem, vagy az?

**Comment by borsodi-koppany** [comment]
azt már elintéztem

**Comment by borsodi-koppany** [comment]
amit csináltam pull requestet azt be mergelnéd?

**Comment by feher-kristof1** [comment]
Yep
